### ISSUE TITLE
collapsible Accordion

### ISSUE THREAD

**Issue by RD1612** [qcubed/bootstrap#1]
Hi, 
I've got a problem with the accordion controller.
Is there a possibility to add collapsible:true to the accordion ? 
I want the accordion to close when you click a second time on the header.
I was looking in the code, but i don't see where i can fix this.
If anybody can help me it would be really appreciated.

Thanks in advance

**Comment by kukrik** [comment]
Hi, I do not know if you are using QCubed Bootstrap. But you can invite your desired event, maybe click a second time to close etc...

Please see for example http://localhost/qcubed_4/vendor/qcubed/bootstrap/examples/bootstrap_ex.php!

Of course, I think there's a little mistake in clicking on the link. In fact, you must be able to click on the tab. This should be improved...

**Comment by RD1612** [comment]
Hi Kukrik, 

I will check if this will fix my problem, but do you have an idea where the JavaScript is called to build the accordion  ? Maybe i can add the functionality to the accordion through that way.

Thanks in advance

**Comment by kukrik** [comment]
Do you use it https://github.com/qcubed/bootstrap? This should work well.

I watched this on https://getbootstrap.com/docs/3.3/javascript/#collapse-example-accordion and I have to take my words back. A link, not a tab, remains for a click.

I got a hundred work, I do not get to everywhere, sorry... But this accordion is in my list of works, but I'll get to work sooner or later.

In any case, this QCubed/Bootstrap/Accordion must resolve your problem.

**Comment by spekary** [comment]
Not sure what accordion you are referring to. Perhaps the version 2 plugin? Or the bootstrap plugin? They work very differently. Please be specific.

**Comment by RD1612** [comment]
Sorry, it was the Bootstrap plugin.
But i think its something in my code, because in the examples the accordion works.
Sorry for the question, but as i said earlier in the post. I'm pretty new with QCubed.

Thanks for the response

**Comment by spekary** [comment]
No problem. For future reference, the general approach of the whole QCubed bootstrap library is to output tags that match the bootstrap documentation as to how tags should be output. It then will use a bit of the javascript that bootstrap provides to keep track of what the user does. For example, if the user collapses something, we will try to keep track of that so that when you query the accordion object on the PHP side, it will know what state the accordion is in. Other than that, there is no magic to it. All formatting and mechanics should be handled entirely by bootstrap. If there is a problem, either the bootstrap.css or bootstrap.js is not loaded properly, or we simply have a bug in how we are outputting the html such that it isn't outputting the correct attributes that bootstrap expects.

**Comment by RD1612** [comment]
Ok thanks
